export type Level = {
  id: string;
  title: string;
  concept: string;
  instructions: string;
  starterCode: string;
  checks: string[];
  hints: string[];
  visualizer: "variables" | "sequence" | "mapping" | "output";
  successMessage: string;
};

export const levels: Level[] = [
  {
    id: "variables-01",
    title: "变量与执行状态",
    concept: "变量",
    instructions: "把 x 改成 10，并运行代码。观察右侧变量快照如何从代码里提取当前状态。",
    starterCode: "x = 0\nprint(x)",
    checks: ["创建变量 x，并让它等于 10"],
    hints: ["这一关只需要改变量的值。", "保留变量名 x，让等号右侧变成目标数字。", "运行前可以让代码看起来像 x = 10。"],
    visualizer: "variables",
    successMessage: "通过。你已经看到 Python 代码执行后，变量会以运行时对象的形式留在命名空间里。",
  },
  {
    id: "types-01",
    title: "基础类型",
    concept: "类型",
    instructions: "创建 count、name、active 三个变量，分别使用数字、字符串和布尔值。",
    starterCode: "count = 0\nname = \"\"\nactive = False",
    checks: ["count 等于 3", "name 等于 Python", "active 为 True"],
    hints: ["三个变量分别要使用数字、字符串和布尔值。", "字符串需要用引号包起来，布尔值首字母大写。", "可以写成 count = 3、name = \"Python\"、active = True。"],
    visualizer: "variables",
    successMessage: "通过。Python 不需要声明变量类型，但每个值在运行时仍然有明确类型。",
  },
  {
    id: "strings-01",
    title: "字符串格式化",
    concept: "字符串",
    instructions: "使用 f-string 生成 message，让它等于 Hello, Ada!",
    starterCode: "name = \"Ada\"\nmessage = \"\"",
    checks: ["message 等于 Hello, Ada!"],
    hints: ["message 需要根据 name 生成。", "f-string 可以把变量放进字符串里。", "试试 message = f\"Hello, {name}!\"。"],
    visualizer: "variables",
    successMessage: "通过。f-string 是 Python 中最常用、最清晰的字符串插值方式。",
  },
  {
    id: "lists-01",
    title: "列表与索引",
    concept: "列表",
    instructions: "修改 numbers，让它包含 1 到 5，并创建 middle 保存中间三个元素。",
    starterCode: "numbers = []\nmiddle = []",
    checks: ["numbers 等于 [1, 2, 3, 4, 5]", "middle 等于 [2, 3, 4]"],
    hints: ["先把完整列表 numbers 准备好。", "列表切片可以用起点和终点取中间部分。", "middle 可以来自 numbers[1:4]。"],
    visualizer: "sequence",
    successMessage: "通过。列表适合表达有序集合，切片能稳定取出子序列。",
  },
  {
    id: "dicts-01",
    title: "字典与结构化数据",
    concept: "字典",
    instructions: "从 profile 中取出 name 和 score，生成 summary 字典。",
    starterCode: "profile = {\"name\": \"Lin\", \"score\": 8}\nsummary = {}",
    checks: ["summary.name 等于 Lin", "summary.passed 为 True"],
    hints: ["summary 也应该是一个字典。", "可以从 profile 里读取 name 和 score。", "passed 可以由 profile[\"score\"] >= 6 得到。"],
    visualizer: "mapping",
    successMessage: "通过。字典把数据从有序集合推进到键值结构，很适合表达记录。",
  },
  {
    id: "conditionals-01",
    title: "条件分支",
    concept: "条件",
    instructions: "根据 score 设置 grade：90 及以上为 A，60 及以上为 B，否则为 C。",
    starterCode: "score = 86\ngrade = \"\"",
    checks: ["score 为 86 时 grade 等于 B"],
    hints: ["用 if / elif / else 表达分数区间。", "先判断最高分段，再判断下一档。", "86 小于 90 且大于等于 80，所以 grade 应该是 \"B\"。"],
    visualizer: "variables",
    successMessage: "通过。条件分支把数据状态映射成业务分类，是脚本逻辑的核心。",
  },
  {
    id: "loops-01",
    title: "循环与过滤",
    concept: "循环",
    instructions: "从 numbers 中筛选偶数，保存到 evens。",
    starterCode: "numbers = [1, 2, 3, 4, 5, 6]\nevens = []",
    checks: ["evens 等于 [2, 4, 6]"],
    hints: ["需要遍历 numbers。", "偶数可以用 number % 2 == 0 判断。", "符合条件时用 evens.append(number) 加入结果。"],
    visualizer: "sequence",
    successMessage: "通过。循环让你对集合里的每个元素应用同一套规则。",
  },
  {
    id: "functions-01",
    title: "函数",
    concept: "函数",
    instructions: "实现 add_tax(price)，返回加 10% 税后的价格。",
    starterCode: "def add_tax(price):\n    return price\n\nresult = add_tax(100)",
    checks: ["result 等于 110.0"],
    hints: ["函数返回的是含税价格。", "10% 税意味着乘以 1.1。", "让 add_tax 返回 price * 1.1。"],
    visualizer: "variables",
    successMessage: "通过。函数把一段规则变成可复用接口，后续关卡会用它组织更真实的脚本。",
  },
  {
    id: "errors-01",
    title: "异常与防御",
    concept: "异常",
    instructions: "实现 safe_divide(a, b)，当 b 为 0 时返回 None。",
    starterCode: "def safe_divide(a, b):\n    return a / b\n\nresult = safe_divide(10, 0)",
    checks: ["result 为 None"],
    hints: ["先处理 b 为 0 的特殊情况。", "遇到无法计算的情况可以 return None。", "在除法之前写 if b == 0: return None。"],
    visualizer: "variables",
    successMessage: "通过。异常处理让脚本面对坏输入时仍能给出可预测结果。",
  },
  {
    id: "challenge-01",
    title: "综合挑战：日志统计",
    concept: "综合",
    instructions: "统计 logs 中 ERROR 的数量，保存到 error_count。",
    starterCode: "logs = [\"INFO start\", \"ERROR disk\", \"INFO retry\", \"ERROR timeout\"]\nerror_count = 0",
    checks: ["error_count 等于 2"],
    hints: ["需要遍历每一条日志字符串。", "判断字符串里是否包含 ERROR。", "每发现一次 ERROR，就让 error_count 增加 1。"],
    visualizer: "output",
    successMessage: "通过。你已经把字符串、列表、循环和变量组合成了一个小型 Python 脚本。",
  },
  {
    id: "string-methods-01",
    title: "字符串方法",
    concept: "字符串",
    instructions: "清理 raw 字符串，生成 topics 列表，让每个主题去掉空格并首字母大写。",
    starterCode: "raw = \"  python,testing,debugging  \"\ntopics = []",
    checks: ["topics 等于 ['Python', 'Testing', 'Debugging']"],
    hints: ["先去掉 raw 两端空格。", "split(',') 可以按逗号拆成多个字符串。", "对每一项 strip() 后再 title()。"],
    visualizer: "sequence",
    successMessage: "通过。字符串方法很适合把粗糙文本清洗成稳定结构。",
  },
  {
    id: "comprehensions-01",
    title: "列表推导式",
    concept: "列表推导式",
    instructions: "用一行列表推导式筛选偶数，并保存它们的平方到 squares。",
    starterCode: "numbers = [1, 2, 3, 4, 5, 6]\nsquares = []",
    checks: ["squares 等于 [4, 16, 36]"],
    hints: ["先想清楚普通循环会怎么写。", "列表推导式格式是 [表达式 for 变量 in 列表 if 条件]。", "表达式可以是 number * number，条件可以是 number % 2 == 0。"],
    visualizer: "sequence",
    successMessage: "通过。列表推导式把“遍历、过滤、变换”压缩成了清晰的一行。",
  },
  {
    id: "nested-data-01",
    title: "嵌套数据",
    concept: "嵌套结构",
    instructions: "从 students 中找出分数最高的学生，并把 name 和 score 保存到 summary 字典。",
    starterCode: "students = [{\"name\": \"Ada\", \"score\": 9}, {\"name\": \"Lin\", \"score\": 6}]\nsummary = {}",
    checks: ["summary 记录最高分学生"],
    hints: ["students 是列表，里面每一项都是字典。", "可以用 max 配合 key 找最高分。", "summary 只需要保存最高分学生的 name 和 score。"],
    visualizer: "mapping",
    successMessage: "通过。真实 Python 任务里经常会处理列表套字典这样的结构。",
  },
  {
    id: "file-lines-01",
    title: "模拟文件行处理",
    concept: "文本行处理",
    instructions: "把 lines 当作文件内容，筛选出 ERROR 行保存到 errors，并统计 error_count。",
    starterCode: "lines = [\"INFO start\", \"WARN cache\", \"ERROR disk\", \"ERROR timeout\"]\nerrors = []\nerror_count = 0",
    checks: ["errors 只包含 ERROR 行", "error_count 等于 2"],
    hints: ["可以先遍历每一行。", "startswith('ERROR') 能判断一行是否以 ERROR 开头。", "error_count 可以直接用 len(errors)。"],
    visualizer: "sequence",
    successMessage: "通过。很多自动化脚本本质上就是读取一批文本行、过滤、统计。",
  },
  {
    id: "challenge-02",
    title: "综合挑战：订单汇总",
    concept: "综合",
    instructions: "计算订单总价 total，并生成 labels 描述每个商品的数量。",
    starterCode: "orders = [{\"item\": \"book\", \"price\": 30, \"qty\": 2}, {\"item\": \"pen\", \"price\": 5, \"qty\": 4}]\ntotal = 0\nlabels = []",
    checks: ["total 等于 80", "labels 描述每个订单数量"],
    hints: ["每个订单的小计是 price * qty。", "total 可以用 sum 汇总所有小计。", "labels 可以用 f-string 生成，比如 book x2。"],
    visualizer: "mapping",
    successMessage: "通过。你已经把嵌套数据、循环、推导式和字符串格式化组合成了更接近业务脚本的小任务。",
  },
];
